# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
  
    config.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.memory = 1024
      vb.cpus = 2      
    end
  
    ## master.hl.local
    config.vm.define "master.hl.local" do |machine|
      machine.vm.hostname = "master.hl.local"
      machine.vm.box_check_update = true
      machine.vm.box = "centos/7"
      machine.vm.network "private_network", ip: "192.168.58.30"
  
      machine.vm.provider :virtualbox do |vb|
             vb.memory = 2048
      end
    end
  
    ## node01.hl.local
    config.vm.define "node01.hl.local" do |machine|
      machine.vm.hostname = "node01.hl.local"
      machine.vm.box_check_update = true
      machine.vm.box = "centos/7"
      machine.vm.network "private_network", ip: "192.168.58.31"
    end
  
    ## node02.hl.local
    config.vm.define "node02.hl.local" do |machine|
      machine.vm.hostname = "node02.hl.local"
      machine.vm.box_check_update = true
      machine.vm.box = "centos/7"
      machine.vm.network "private_network", ip: "192.168.58.32"
    end
  end
  